on:
    push:
    # supplies a button in gh for manual running
    workflow_dispatch:
    schedule:
        # - cron:  '0 0 * * 0' # every week 

# lets gh change files
permissions: write-all

# what happens when the code runs
jobs:
    run:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-python@v4
            # run and assign to a file called data
            # run: python start.py > data.json
            - run: python start.py > data/$(date +%Y%m%d-%H%M%S).json
            # add the data to our repository
            - run: |-
                  git config user.name 'GitHub Actions'
                  git config user.email 'actions@users.noreply.github.com'
                  git add -A
                  git commit -m 'Updates' || exit 0
                  git push
